<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DireccionSeeder extends Seeder
{

    public function run(): void
    {
        $direcciones = [
            [
                'calle' => 'Av. Reforma',
                'numero' => 100,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06000,
                'longitud' => -99.1332,
                'latitud' => 19.4326,
                'fotografia_id' => null,
                'referencia' => 'Frente a la torre',
            ],
            [
                'calle' => 'Insurgentes Sur',
                'numero' => 200,
                'colonia' => 'Del Valle',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 03100,
                'longitud' => -99.162,
                'latitud' => 19.387,
                'fotografia_id' => null,
                'referencia' => 'Cerca del metro',
            ],
            [
                'calle' => 'Av. Juárez',
                'numero' => 50,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Niños heroes',
                'numero' => 51,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Av. Olmeca',
                'numero' => 90,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Juan Escutia',
                'numero' => 5,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Lomas Sotelo',
                'numero' => 50,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Av. de las arboleras',
                'numero' => 8,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Morelos',
                'numero' => 44,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Av. Reforma',
                'numero' => 22,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06000,
                'longitud' => -99.1332,
                'latitud' => 19.4326,
                'fotografia_id' => null,
                'referencia' => 'Frente a la torre',
            ],
            [
                'calle' => 'Insurgentes Sur',
                'numero' => 11,
                'colonia' => 'Del Valle',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 03100,
                'longitud' => -99.162,
                'latitud' => 19.387,
                'fotografia_id' => null,
                'referencia' => 'Cerca del metro',
            ],
            [
                'calle' => 'Av. Juárez',
                'numero' => 66,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Niños heroes',
                'numero' => 5,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Av. Olmeca',
                'numero' => 6,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Juan Escutia',
                'numero' => 8,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Lomas Sotelo',
                'numero' => 56,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Av. de las arboleras',
                'numero' => 85,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
            [
                'calle' => 'Morelos',
                'numero' => 150,
                'colonia' => 'Centro',
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 06010,
                'longitud' => -99.140,
                'latitud' => 19.435,
                'fotografia_id' => null,
                'referencia' => 'Junto al parque',
            ],
        ];

        for ($i = 4; $i <= 20; $i++) {
            $direcciones[] = [
                'calle' => "Calle Falsa $i",
                'numero' => $i * 10,
                'colonia' => "Colonia $i",
                'municipio' => 'Ciudad de México',
                'estado' => 'CDMX',
                'cp' => 10000 + $i,
                'longitud' => -99.100 + ($i * 0.01),
                'latitud' => 19.400 + ($i * 0.01),
                'fotografia_id' => null,
                'referencia' => "Referencia $i",
            ];
        }

        foreach ($direcciones as $direccion) {
            DB::table('direccion')->insert($direccion);
        }

        $this->command->info(count($direcciones).' direcciones creadas exitosamente!');
    }
}

